### ISSUE TITLE
issue-4 Create Content Management System Platform

### ISSUE THREAD

**Issue by wet000** [wet000/framework#9]
Create a general purpose parent content management system platform that other platforms can extend with various CMS implementations.

**Comment by wet001** [comment]
Finished creating a rough draft of a simple CMS service using JSON API and JSON API User plugin for WordPress. Still have a few issues to resolve and more functionality to implement. This is in a stable state for now, so I'm creating a pull request for it.

**Comment by wet000** [comment]
This issue is deprecated now that all components have been split off into their own repositories.
